spring:
    jpa:
        show-sql: true
        hibernate:
            ddl_auto: create-drop
            naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
            default_schema: public

swagger:
    title: Calcard Spring Angular
    description: REST API
    version: 1.0
