version: '2'
services:
  calcard-frontend:
    build: calcard-frontend/.
    ports:
      - "80:80"
    depends_on:
      - calcard-backend
  calcard-backend:
    build: calcard-backend/.
    ports:
      - "8080:8080"
    depends_on:
      - calcard-db
  calcard-db:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calcard